#CueTrans Properties


IPAddress=172.25.131.180
Port=8080
FileUploadPath=C:/FuelTrans/apache-tomcat-9.0.0.M4/webapps/FuelTrans/temp
filePath=C:/FuelTrans/apache-tomcat-9.0.0.M4/webapps/FuelTrans/temp
TimeOut=300000
AllowedFileExt=txt,xls,doc,docx,xlsx,pdf,jpg,png
MaxUploadFileSize=2
TaskValidate=Y
tenantId=cuecent_tenant
CaptchaValidate=Y
MultiTenancy=N
AuthTokenValidate=N
ADAuthFlag=false

