#CueTrans Properties

IPAddress=172.25.130.37
Port=8080
IPAddressRest=localhost
PortRest=8000
FileUploadPath=D:/NIIMS/Apache-Tomcat-9.0.27/webapps/Nayara/temp
filePath=D:/NIIMS/Apache-Tomcat-9.0.27/webapps/Nayara/temp
FilePath=D:/NIIMS/Apache-Tomcat-9.0.27/webapps/Nayara/temp
ServerFileUploadPath=D:/NIIMS/Apache-Tomcat-9.0.27/webapps/Nayara/Documents
TimeOut=300000
AllowedFileExt=pdf,jpg,png,zip
FileNameLength=30
MaxUploadFileSize=2
TaskValidate=Y
tenantId=cuecent_tenant
CaptchaValidate=N
MultiTenancy=N
AuthTokenValidate=Y
ADAuthFlag=false
isTrackServerHit=Y

pdodbdriver=oracle.jdbc.driver.OracleDriver
pdodburl=jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = mus-dbvip-302.pdo.shell.om)(PORT = 1521)) (ADDRESS = (PROTOCOL = TCP)(HOST = mus-dbvip-102.pdo.shell.om)(PORT = 1521)) (ADDRESS = (PROTOCOL = TCP)(HOST = mus-db-401.pdo.shell.om)(PORT = 1521)) (ADDRESS = (PROTOCOL = TCP)(HOST = mus-dbvip-201.pdo.shell.om)(PORT = 1521)) (ADDRESS = (PROTOCOL = TCP)(HOST = mus-dbc1vip-312.pdo.shell.om)(PORT = 1521)) (CONNECT_DATA =(SERVER = DEDICATED) (SERVICE_NAME = TMS631.WORLD)))
pdodbuserId=tm4pl_prod
pdodbpassword=prod_tm4pl
PROXY_IP=148.151.141.5
PROXY_PORT=8080
requestURL=https://pdo.cuetrans.com/CueTrans/CueTransSAP/sap
userId=ys2nyMYGrDC0zFwp1XVXTA==
password=scKe1/GLf4wG2OubCWQnBg==

JDBCURL=jdbc:oracle:thin:@cuetranspdoprod.cdmgnqqkccnr.eu-central-1.rds.amazonaws.com:1521:orcl
DBUSERNAME=PDO_STAGEDEMOCOE
DBPASSWORD=PDO_STAGEDEMOCOE
EDIOUTBOXPATH=D:/PDO/EDI_INTEGRATION/214/OUTBOX/
LOGPATH=D:/PDO/EDI_INTEGRATION/214/OUTBOX/LOG/


